### ISSUE TITLE
DfaToFullDfa algo is strange

### ISSUE THREAD

**Issue by octomarat** [YaccConstructor/YC.FST#4]
See example 7.10.a here http://mathhelpplanet.com/static.php?p=determinizatsiya-konechnykh-avtomatov

DfaToFullDfa builds some new FSA from the one passes to it, and I'm not completely understand what exactly it returns. Maybe it is a wrong understanding of the term "full dfa" or some other thing is assumed under that term.

**Comment by polubelova** [comment]
I removed extra stuff in function DfaToFullDfa. Now it is easy to undenstand the logic of this function. 

In current implementation we don't use additional state (if you look at your example).

**Comment by octomarat** [comment]
Suppose we have FSA F1 with 2 states  - 0 and 1, 0 is initial and 1 is final, one transition from 0 to 1 by symbol "a", and let the alphabet be A = {a, b}. Out FSA accepts only 1 word "a", so defines one-word regular language. We want to make it completely determined.
In your current algo we get the following FSA F2 as the output of the DfaToFullDfa function: the same as F1 with additional transitions from 0 to 0 by "b", from 1 to 1 by "a" and from 1 to 1 by "b". Resulting FSA defines the following regular lanuage: (b)*a(A)*. This language is not the same as the language defined by F1.
If I correctly understand the process of making FSA completely determined it must define the same language.
