### ISSUE TITLE
Equals for NfaNodeIdSet always returns false

### ISSUE THREAD

**Issue by bronti** [YaccConstructor/YC.FST#7]
Overrided Equals for NfaNodeIdSet in FSA/GraphBasedFsa.fs always returns false.

        let n = yr.Length

        xr.Length = n &&
        (let rec go i = (i < n) && xr.[i] = yr.[i] && go (i+1) 
        go 0)

Even if `xr` and  `yr` are equal, `(i < n)` eventually will become false making `go i` also false.

Possible fix:

        let n = yr.Length

        xr.Length = n &&
        (let rec go i = (i >= n) || xr.[i] = yr.[i] && go (i+1) 
        go 0)

**Comment by kajigor** [comment]
Proposed fix seams to be ok. Please, fix the bug and check that it does not break anything.

**Comment by kajigor** [comment]
Consider creating the bug here: https://github.com/fsprojects/FsLexYacc/blob/master/src/FsLex/fslexast.fs
